export const ROUTES = {
  home: "/",
  categories: "/categories",
  products: "/products",
  category: "/categories/:categoryId",
  product: "/products/:productId",
  login: "/login",
  signup: "/signup",
  orders: "/orders",
  complains: "/complains",
  search: "/search",
  Login: "/login",
  SingUp: "/signup",
  yourHeader: "/orderHeader",
};
